### ISSUE TITLE
Extension Questions

### ISSUE THREAD

**Issue by webmastak** [andia89/order-icons#1]
I correctly understood that you can change the order of these icons?
[![https://i.imgur.com/DWyFMfK.png](https://i.imgur.com/DWyFMfK.png)](https://i.imgur.com/DWyFMfK.png)

Tell me your extension will work with a gnome shell 3.34?
You can show an example of what the **ordering-override.keyfile** file should be.

**Comment by wa4557** [comment]
Hello, 

yes that's the idea. Should work with 3.34

My keyfile looks like that:

a11y=1
dropbox=2
freonMenu=3
diodonGnomeIndicator=4
remmina-icon=7
Caffeine=5
variety=6
vericold=9
TeamViewer=8
Franz1=10
unitymail=11
keyboard=12
dateMenu=13
aggregateMenu=14

activities=1
appMenu=2


but you will have to play with that because you need the correct name of the icons (in your picture I only see aggregateMenu and keyboard)...

You can find that out in lookingGlass (Alt+F2 "lg") in the evaluator with 

Main.panel.statusArea which gives you the items, and then you need to find the _indicator.id for each icon

I will try to make that a bit more user friendly if possible!

**Comment by webmastak** [comment]
Thank you for the quick and detailed answer.

**Comment by andia89** [comment]
sure :)

Here you go
![Screenshot from 2019-11-04 16-24-19](https://user-images.githubusercontent.com/6475757/68132827-a3e0d280-ff1f-11e9-95df-4d0077b68bb5.png)

This gives me a panel that looks like that:

![Screenshot from 2019-11-04 16-24-45](https://user-images.githubusercontent.com/6475757/68132839-a6432c80-ff1f-11e9-971c-48a77242a030.png)

**Comment by viggy96** [comment]
How exactly do I find the icon names for icons that are statusbar icons rather than icons from a gnome extension? Like I've got steam and nextcloud icons, and those aren't produced by an extension, but rather are appindicator icons created by the program itself. There isn't an 'extension.js' I can look in to get the icon name for those.

**Comment by webmastak** [comment]
I do not know. 

But for tray icons, I use TopIcons Plus and Minimize to Tray extensions.

**Comment by andia89** [comment]
I made a workaround to figure out how to figure out the proper names (last commit)

activate the extension open a terminal, and type `journalctl /usr/bin/gnome-shell -f`
then open any program that adds an indicator to the panel and you should see something like:

```
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: activities 
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: appMenu
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: dateMenu
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: dwellClick
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: a11y
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: keyboard
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: aggregateMenu
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: system-monitor
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: Caffeine
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: diodonGnomeIndicator
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: Insync
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: ownCloud
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: unity-mail
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: remmina-icon
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: Franz1
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: adr
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: vericold
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: dropbox
Nov 05 11:48:45 andreas-office gnome-shell[18321]: Order application icons: TeamViewer

```

which are exactly the names you have to put in the file

**Comment by andia89** [comment]
see the updated readme for insctructions. It should be much easier now!

**Comment by frost19k** [comment]
@andia89 Do I explicitly have to record every icon from the journalctl command in the keyfile? 

Let's say, from your example, I only care that aggregateMenu is right-most then, moving left, I want Caffeine followed by ownCloud. I do not care about the order of any of the other icons.

**Comment by andia89** [comment]
@frost19k 
you don't have to specifiy the rest, but then they will be ordered alphabetically and the order will always remain the same. so you can just specifiy the last ones and then the rest will be done by itself
