### ISSUE TITLE
Extension makes app icon and application name visible in lock screen

### ISSUE THREAD

**Issue by vk001716** [andia89/order-icons#5]
This is a security flaw as this extension makes the app icon and application name visible on the lock screen. I may be showing other user data in the top bar, not sure about that.

Also, this extension doesn't respect the changes made by other extensions.

Adding key file is tricky and not everyone is so technical to make this file. You can add this feature in the setting option for this extension (by running journalctl .. command) and then giving user the option to rearrange the order.

Like the idea for this application.

**Comment by andia89** [comment]
Hmm. I can't reproduce the lock-screen issue. For me all the tray icons are gone when I lock my computer, the extension also shouldn't really do that since it is basically just overloading a function and does not really change anything substantial. 

The fact that it does not respect the changes made by other extensions is by design. This extension (at least for my usecase) should be the one making the decision how icons are ordered, I don't want every extension / app to decide where they should show up. I won't change that here

And yeah the keyfile is a semi temporary solution, since it is how it was in old unity times. I might write a preferences file but gjs is not my strong suit.

**Comment by andia89** [comment]
I reworked the extension quite significantly and addressed the points raised. Please check it out and open a new issue for any problems
